### PR TITLE
Add license file

### LINKED ISSUE #78: Add license files

### PR DESCRIPTION
**Pull request by AlexxNica**
Fixes #78

### CODE REVIEW

**Review by SgtPooki — CHANGES_REQUESTED** [review]
These should be the same as 

https://github.com/ipfs/aegir/blob/master/LICENSE-MIT
https://github.com/ipfs/aegir/blob/master/LICENSE
https://github.com/ipfs/aegir/blob/master/LICENSE-APACHE

**Comment by AlexxNica** [comment]
@SgtPooki it seems the [LICENSE-APACHE](https://github.com/ipfs/aegir/blob/master/LICENSE-APACHE) from that repo doesn't get recognized by GitHub. Should we add a format that gets recognized by GitHub or just ignore it?
image

**Comment by SgtPooki** [comment]
> @SgtPooki it seems the [LICENSE-APACHE](https://github.com/ipfs/aegir/blob/master/LICENSE-APACHE) from that repo doesn't get recognized by GitHub. Should we add a format that gets recognized by GitHub or just ignore it? 

Good callout. We should ignore it here, and open an issue on aegir.

**Comment by SgtPooki** [comment]
created https://github.com/ipfs/aegir/issues/1198

**Review by SgtPooki — CHANGES_REQUESTED** [review]
looks like we're still missing the files we should have

**Comment by AlexxNica** [comment]
> looks like we're still missing the files we should have

@SgtPooki aren't those at #338? I believe you have to accept that one so that the updates show up on this PR, since I don't have permission to push to this branch directly.

**Review by SgtPooki — APPROVED** [review]

**Pull request merged**
